### PR TITLE
Added modules, added data directory and fixed File issue.

### PR DESCRIPTION
**Pull request by rdridder**
Hi @copych, @midilab,

This version of the code compiles. I have only checked in the serial monitor that the project actually starts up and it does. I will continue testing but I had some issues with getting the S3 board to work. The IDE would upload the code but nothing would actually happen.

@copych _uCtrl/module/ contains whole huge libraries like U8g2 and SdFat. What is the reason for you to keep all these files?_ 
You can create user interfaces with the uCtrl project, if you check src\interface\midilab a default interface is created to be able to control the sequencer, see: [docs](https://github.com/midilab/aciduino/tree/master/v2), you will find the breadboard layouts with the buttons and the oled screen. If you create that you will have a sequencer and hardware running out of the box.

I will try to get the default sequencer controls running so we have a good reference to start from. After that we can focus on integrating but I would also like to create a good hardware user interface with controls suitable for the 303 and 808.

### CODE REVIEW

**Review by copych — APPROVED** [review]
Great!

**Comment by rdridder** [comment]
@copych 
I will try to get a task running so it will also run the Aciduino code. The loop function is not being called because tasks are used. If I have that working I will submit another pull request.

**Comment by copych** [comment]
@rdridder @midilab please, you probably already know where to catch 'midi' events. The idea is that in AcidBox' `midi_handle.ino` there're handlers for midi events:
```
inline void handleNoteOn(uint8_t inChannel, uint8_t inNote, uint8_t inVelocity);
inline void handleNoteOff(uint8_t inChannel, uint8_t inNote, uint8_t inVelocity);
inline void handleCC(uint8_t inChannel, uint8_t cc_number, uint8_t cc_value);
void handleProgramChange(uint8_t inChannel, uint8_t number);
inline void handlePitchBend(uint8_t inChannel, int number) ;
```
and the easiest way to make interconnection between the sequencer and the synth is to bind them right before the sequencer really transmits midi messages (forgive my ignorance).

**Comment by copych** [comment]
> The loop function is not being called because tasks are used. If I have that working I will submit another pull request.

I was quite sure it worked, cause core1 task had `taskYIELD();` allowing other tasks to run. If not, it's easy to move everything needed to the `audio_task2` `while(true)` cycle.

**Comment by rdridder** [comment]
> I was quite sure it worked, cause core1 task had `taskYIELD();` allowing other tasks to run. If not, it's easy to move everything needed to the `audio_task2` `while(true)` cycle.

I was investigating a bit more and it seems that my chip kept crashing. I rolled back some code and now at least the tasks seems to run again. I was probably mistaken but I will dig a bit more.

**Comment by copych** [comment]
Also there might be not enough of stack memory for a loop task (setup() and loop() actually). They made a macro for such cases `SET_LOOP_TASK_STACK_SIZE(bytes_to_allocate);`

**Pull request merged**
